main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),

    # user

    path('user/login/', views.user_login, name='user_login'),
    path('user/logout/', views.user_logout, name='user_logout'), # r
    path('user/register/', views.user_register, name='user_register'), 
    # path('user/update/', views.user_update, name='user_update'), # r
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2'
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError(
                    'já existe esse e-mail',
                    code='invalid'
                )
            )

        return email

main/views.py
from django.shortcuts import render

# Create your views here.

main/views/main_views.py
from django.shortcuts import render

def index(request):
    context = {
        'title': 'Home'
    }
    return render(
        request,
        'main/index.html',
        context
    )

main/views/user_forms.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse
from main.forms import RegisterForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages

@login_required(login_url='main:user_login')
def user_logout(request):
    auth.logout(request)
    return redirect('main:index')


def user_register(request):
    form = RegisterForm()
    form_action = reverse('main:user_register')
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'conta registrada com sucesso')
            return redirect('main:user_login')
        
    context = {
        'title': 'Register',
        'form': form,
        'form_action': form_action
    }

    return render(
        request, 
        'user/register.html',
        context
    )


def user_login(request):
    form = AuthenticationForm(request)
    
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request, 'logado com sucesso')
            return redirect('main:index')
    
    context = {
        'title': 'Login',
        'form': form
    }
    return render(
        request,
        'user/login.html',
        context
    )

main/templates/main/index.html
{% extends 'global/base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>oi</h1>
    {% else %}
        {% include 'user/partials/_not-logged.html' %}
    {% endif %}
{% endblock content %}

main/templates/main/partials/_not-logged.html
<p>
    Você não está logado. clique
    <a href="#">aqui</a>
    para efetuar o login
</p>

main/templates/user/login.html
{% extends 'global/base.html' %}

{% block content %}
    <h1>Login</h1>

    {% if user.is_authenticated %}
        {% include 'user/partials/_already-logged.html' %}
    {% else %}
        {% include 'user/partials/_user-form.html' %}
    {% endif %}

{% endblock content %}

main/templates/user/partials/_already-logged.html
<p>
    Você já está logado. clique
    <a href="{% url 'main:user_logout' %}">aqui</a>
    para sair.
</p>

main/templates/user/partials/_not-logged.html
<p>
    Você não está logado. clique
    <a href="{% url 'main:user_login' %}">aqui</a>
    para efetuar o login
</p>

main/templates/user/partials/_user-form.html
<form 
    action="{{ form_action }}" 
    method="POST" 
>
    {% csrf_token %}

    <!-- por padrao form vem como .as_table -->
    <div class="form-content">
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
                {{ field }}
                {{ field.errors }}
                {% if field.help_text %}
                    <p class="help-text">
                        {{ field.help_text}}
                    </p>
                {% endif %}
            </div>
        {% endfor %}
    </div>

    {% if form.non_field_errors %}
        <div class="form-content">
            <div class="form-group">
                <div class="message error">
                    {{ form.non_field_errors }}
                </div>
            </div> 
        </div>
    {% endif %}

    <div class="form-content">
        <div class="form-group">
            <button class='btn' type="submit">Send</button>
        </div> 
    </div>
</form>

main/templates/user/register.html
{% extends 'global/base.html' %}

{% block content %}
    <h1>Register</h1>

    {% include 'user/partials/_user-form.html' %}
{% endblock content %}